2024-10-30 13:21:26 - INFO - pika.adapters.utils.connection_workflow: Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-10-30 13:21:26 - INFO - pika.adapters.utils.io_services_utils: Socket connected: <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 60570), raddr=('127.0.0.1', 5672)>
2024-10-30 13:21:26 - INFO - pika.adapters.utils.connection_workflow: Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x721c029f8a60>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x721c029f8a60> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-10-30 13:21:26 - INFO - pika.adapters.utils.connection_workflow: AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x721c029f8a60> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-10-30 13:21:26 - INFO - pika.adapters.utils.connection_workflow: AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x721c029f8a60> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-10-30 13:21:26 - INFO - pika.adapters.blocking_connection: Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x721c029f8a60> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-10-30 13:21:26 - INFO - pika.adapters.blocking_connection: Created channel=1
2024-10-30 13:21:26 - INFO - client: Connected to RabbitMQ and listening on queue: amq.gen-TZ-ovu6ChOvIRQa0CoR9HQ
2024-10-30 13:21:26 - INFO - client: Sent 'Hi' to server for readiness check.
2024-10-30 13:21:26 - INFO - client: Received response: Hello for request ID: 47fa2b04-8f97-430f-9fd8-c57471832b49
2024-10-30 13:21:26 - ERROR - client: Error processing response: wrapped C/C++ object of type Communicate has been deleted
2024-10-30 13:21:26 - ERROR - client: Failed to connect to RabbitMQ: wrapped C/C++ object of type Communicate has been deleted
2024-10-30 13:21:41 - INFO - pika.adapters.utils.connection_workflow: Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-10-30 13:21:41 - INFO - pika.adapters.utils.io_services_utils: Socket connected: <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 34950), raddr=('127.0.0.1', 5672)>
2024-10-30 13:21:41 - INFO - pika.adapters.utils.connection_workflow: Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7dc69748d360>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7dc69748d360> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-10-30 13:21:41 - INFO - pika.adapters.utils.connection_workflow: AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7dc69748d360> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-10-30 13:21:41 - INFO - pika.adapters.utils.connection_workflow: AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7dc69748d360> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-10-30 13:21:41 - INFO - pika.adapters.blocking_connection: Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7dc69748d360> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-10-30 13:21:41 - INFO - pika.adapters.blocking_connection: Created channel=1
2024-10-30 13:21:41 - INFO - client: Connected to RabbitMQ and listening on queue: amq.gen-IPjAX_lZ5HdOT3oER4u-Pw
2024-10-30 13:21:41 - INFO - client: Sent 'Hi' to server for readiness check.
2024-10-30 13:21:41 - INFO - client: Received response: Hello for request ID: 640dbefc-a8c5-4eff-9859-c6871b6ffa7a
2024-10-30 13:21:41 - ERROR - client: Error processing response: wrapped C/C++ object of type Communicate has been deleted
2024-10-30 13:21:41 - ERROR - client: Failed to connect to RabbitMQ: wrapped C/C++ object of type Communicate has been deleted
2024-10-30 13:28:17 - INFO - pika.adapters.utils.connection_workflow: Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-10-30 13:28:17 - INFO - pika.adapters.utils.io_services_utils: Socket connected: <socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 35068), raddr=('127.0.0.1', 5672)>
2024-10-30 13:28:17 - INFO - pika.adapters.utils.connection_workflow: Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x76b2237470a0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x76b2237470a0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-10-30 13:28:17 - INFO - pika.adapters.utils.connection_workflow: AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x76b2237470a0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-10-30 13:28:17 - INFO - pika.adapters.utils.connection_workflow: AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x76b2237470a0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-10-30 13:28:17 - INFO - pika.adapters.blocking_connection: Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x76b2237470a0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-10-30 13:28:17 - INFO - pika.adapters.blocking_connection: Created channel=1
2024-10-30 13:28:17 - INFO - client: Connected to RabbitMQ and listening on queue: amq.gen-1mw_hEiw9t0tCauFUR4cKA
2024-10-30 13:28:17 - INFO - client: Sent 'Hi' to server for readiness check.
2024-10-30 13:28:17 - INFO - client: Received response: Hello for request ID: a2288103-5a64-44d8-9cc6-2ae3e8be7b39
2024-10-30 13:28:17 - INFO - client: Server is ready.
2024-10-30 13:28:39 - INFO - pika.adapters.blocking_connection: Closing connection (200): Normal shutdown
2024-10-30 13:28:39 - INFO - pika.channel: Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x76b2237470a0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-10-30 13:28:39 - ERROR - pika.adapters.utils.io_services_utils: _AsyncBaseTransport._produce() failed, aborting connection: error=IndexError('pop from an empty deque'); sock=<socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 35068), raddr=('127.0.0.1', 5672)>; Caller's stack:
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
2024-10-30 13:28:39 - ERROR - pika.channel: Unexpected frame: <METHOD(['channel_number=1', 'frame_type=1', "method=<Basic.CancelOk(['consumer_tag=ctag1.d65256e79ebe4ab38bfb5430e6ec41d4'])>"])>
2024-10-30 13:28:39 - INFO - pika.adapters.utils.io_services_utils: _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=IndexError('pop from an empty deque'); <socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 35068), raddr=('127.0.0.1', 5672)>
2024-10-30 13:28:39 - INFO - pika.channel: Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x76b2237470a0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-10-30 13:28:39 - INFO - pika.adapters.utils.io_services_utils: Deactivating transport: state=1; <socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 35068), raddr=('127.0.0.1', 5672)>
2024-10-30 13:28:39 - INFO - pika.connection: Closing connection (200): 'Normal shutdown'
2024-10-30 13:28:39 - ERROR - pika.adapters.base_connection: connection_lost: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-10-30 13:28:39 - ERROR - client: Error closing connection: 'NoneType' object has no attribute 'write'
2024-10-30 13:28:39 - INFO - pika.connection: AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",); pending-error=ConnectionClosedByClient: (200) 'Normal shutdown'
2024-10-30 13:28:39 - INFO - pika.connection: Stack terminated due to StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-10-30 13:28:39 - INFO - pika.adapters.utils.io_services_utils: Closing transport socket and unlinking: state=2; <socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 35068), raddr=('127.0.0.1', 5672)>
2024-10-30 13:28:39 - ERROR - pika.adapters.blocking_connection: Unexpected connection close detected: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-10-30 13:28:39 - ERROR - client: AMQP Error: Stream connection lost: IndexError('pop from an empty deque')
2024-10-30 13:28:44 - INFO - pika.adapters.utils.connection_workflow: Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-10-30 13:28:44 - INFO - pika.adapters.utils.io_services_utils: Socket connected: <socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 58178), raddr=('127.0.0.1', 5672)>
2024-10-30 13:28:44 - INFO - pika.adapters.utils.connection_workflow: Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7e9ed0f470a0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7e9ed0f470a0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-10-30 13:28:44 - INFO - pika.adapters.utils.connection_workflow: AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7e9ed0f470a0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-10-30 13:28:44 - INFO - pika.adapters.utils.connection_workflow: AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7e9ed0f470a0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-10-30 13:28:44 - INFO - pika.adapters.blocking_connection: Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7e9ed0f470a0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-10-30 13:28:44 - INFO - pika.adapters.blocking_connection: Created channel=1
2024-10-30 13:28:44 - INFO - client: Connected to RabbitMQ and listening on queue: amq.gen-pHRGKG-wuvk52z7-KYVVAQ
2024-10-30 13:28:44 - INFO - client: Sent 'Hi' to server for readiness check.
2024-10-30 13:28:44 - INFO - client: Received response: Hello for request ID: d508373b-0f5c-4409-9a68-5eb7914d6c4f
2024-10-30 13:28:44 - INFO - client: Server is ready.
2024-10-30 13:29:19 - INFO - pika.adapters.blocking_connection: Closing connection (200): Normal shutdown
2024-10-30 13:29:19 - ERROR - pika.channel: Unexpected frame: <METHOD(['channel_number=1', 'frame_type=1', "method=<Basic.CancelOk(['consumer_tag=ctag1.378ff7e85df14ddc82de2dc8b2ccd860'])>"])>
2024-10-30 13:29:19 - ERROR - pika.adapters.utils.io_services_utils: _AsyncBaseTransport._produce() failed, aborting connection: error=IndexError('pop from an empty deque'); sock=<socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 58178), raddr=('127.0.0.1', 5672)>; Caller's stack:
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
2024-10-30 13:29:19 - INFO - pika.adapters.utils.io_services_utils: _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=IndexError('pop from an empty deque'); <socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 58178), raddr=('127.0.0.1', 5672)>
2024-10-30 13:29:19 - INFO - pika.adapters.utils.io_services_utils: Deactivating transport: state=1; <socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 58178), raddr=('127.0.0.1', 5672)>
2024-10-30 13:29:19 - ERROR - pika.adapters.base_connection: connection_lost: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-10-30 13:29:19 - INFO - pika.connection: AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",); pending-error=None
2024-10-30 13:29:19 - INFO - pika.connection: Stack terminated due to StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-10-30 13:29:19 - INFO - pika.adapters.utils.io_services_utils: Closing transport socket and unlinking: state=2; <socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 58178), raddr=('127.0.0.1', 5672)>
2024-10-30 13:29:19 - ERROR - pika.adapters.blocking_connection: Unexpected connection close detected: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-10-30 13:29:19 - ERROR - client: AMQP Error: Stream connection lost: IndexError('pop from an empty deque')
2024-10-30 13:29:19 - ERROR - client: Error closing connection: Channel is closed.
2024-10-30 13:29:50 - INFO - pika.adapters.utils.connection_workflow: Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-10-30 13:29:50 - INFO - pika.adapters.utils.io_services_utils: Socket connected: <socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 53282), raddr=('127.0.0.1', 5672)>
2024-10-30 13:29:50 - INFO - pika.adapters.utils.connection_workflow: Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7a7edb76d8a0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7a7edb76d8a0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-10-30 13:29:50 - INFO - pika.adapters.utils.connection_workflow: AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7a7edb76d8a0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-10-30 13:29:50 - INFO - pika.adapters.utils.connection_workflow: AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7a7edb76d8a0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-10-30 13:29:50 - INFO - pika.adapters.blocking_connection: Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7a7edb76d8a0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-10-30 13:29:50 - INFO - pika.adapters.blocking_connection: Created channel=1
2024-10-30 13:29:50 - INFO - client: Connected to RabbitMQ and listening on queue: amq.gen-v4YvtgLHbdHENIPp3GhE1A
2024-10-30 13:29:50 - INFO - client: Sent 'Hi' to server for readiness check.
2024-10-30 13:29:50 - INFO - client: Received response: Hello for request ID: bfa90412-2a76-4266-a282-053fcad2f393
2024-10-30 13:29:50 - INFO - client: Server is ready.
2024-10-30 13:29:55 - INFO - pika.adapters.blocking_connection: Closing connection (200): Normal shutdown
2024-10-30 13:29:55 - INFO - pika.channel: Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7a7edb76d8a0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-10-30 13:29:55 - INFO - pika.channel: Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7a7edb76d8a0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-10-30 13:29:55 - INFO - pika.connection: Closing connection (200): 'Normal shutdown'
2024-10-30 13:29:55 - INFO - pika.adapters.utils.io_services_utils: Aborting transport connection: state=1; <socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 53282), raddr=('127.0.0.1', 5672)>
2024-10-30 13:29:55 - INFO - pika.adapters.utils.io_services_utils: _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 53282), raddr=('127.0.0.1', 5672)>
2024-10-30 13:29:55 - INFO - pika.adapters.utils.io_services_utils: Deactivating transport: state=1; <socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 53282), raddr=('127.0.0.1', 5672)>
2024-10-30 13:29:55 - INFO - pika.connection: AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByClient: (200) 'Normal shutdown'
2024-10-30 13:29:55 - INFO - pika.connection: Stack terminated due to ConnectionClosedByClient: (200) 'Normal shutdown'
2024-10-30 13:29:55 - INFO - pika.adapters.utils.io_services_utils: Closing transport socket and unlinking: state=3; <socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 53282), raddr=('127.0.0.1', 5672)>
2024-10-30 13:29:55 - INFO - pika.adapters.blocking_connection: User-initiated close: result=BlockingConnection__OnClosedArgs(connection=<SelectConnection CLOSED transport=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>, error=ConnectionClosedByClient: (200) 'Normal shutdown')
2024-10-30 13:29:55 - INFO - client: Connection to RabbitMQ closed.
2024-10-30 13:30:35 - INFO - pika.adapters.utils.connection_workflow: Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-10-30 13:30:35 - INFO - pika.adapters.utils.io_services_utils: Socket connected: <socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 43946), raddr=('127.0.0.1', 5672)>
2024-10-30 13:30:35 - INFO - pika.adapters.utils.connection_workflow: Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x777b42cd18a0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x777b42cd18a0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-10-30 13:30:35 - INFO - pika.adapters.utils.connection_workflow: AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x777b42cd18a0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-10-30 13:30:35 - INFO - pika.adapters.utils.connection_workflow: AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x777b42cd18a0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-10-30 13:30:35 - INFO - pika.adapters.blocking_connection: Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x777b42cd18a0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-10-30 13:30:35 - INFO - pika.adapters.blocking_connection: Created channel=1
2024-10-30 13:30:35 - INFO - client: Connected to RabbitMQ and listening on queue: amq.gen-K0LFNxPDPZdSLvXZZQ3qYA
2024-10-30 13:30:35 - INFO - client: Sent 'Hi' to server for readiness check.
2024-10-30 13:30:35 - INFO - client: Received response: Hello for request ID: 2bbd468b-a128-4dc0-8faf-3120494aba06
2024-10-30 13:30:35 - INFO - client: Server is ready.
2024-10-30 13:30:49 - INFO - pika.adapters.blocking_connection: Closing connection (200): Normal shutdown
2024-10-30 13:30:49 - ERROR - pika.adapters.utils.io_services_utils: _AsyncBaseTransport._produce() failed, aborting connection: error=IndexError('pop from an empty deque'); sock=<socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 43946), raddr=('127.0.0.1', 5672)>; Caller's stack:
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
2024-10-30 13:30:49 - ERROR - pika.channel: Unexpected frame: <METHOD(['channel_number=1', 'frame_type=1', "method=<Basic.CancelOk(['consumer_tag=ctag1.ee0669289977403aae111a2d7657f17e'])>"])>
2024-10-30 13:30:49 - INFO - pika.adapters.utils.io_services_utils: _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=IndexError('pop from an empty deque'); <socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 43946), raddr=('127.0.0.1', 5672)>
2024-10-30 13:30:49 - INFO - pika.channel: Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x777b42cd18a0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-10-30 13:30:49 - INFO - pika.adapters.utils.io_services_utils: Deactivating transport: state=1; <socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 43946), raddr=('127.0.0.1', 5672)>
2024-10-30 13:30:49 - ERROR - pika.adapters.base_connection: connection_lost: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-10-30 13:30:49 - INFO - pika.connection: AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",); pending-error=None
2024-10-30 13:30:49 - INFO - pika.connection: Stack terminated due to StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-10-30 13:30:49 - INFO - pika.adapters.utils.io_services_utils: Closing transport socket and unlinking: state=2; <socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 43946), raddr=('127.0.0.1', 5672)>
2024-10-30 13:30:49 - ERROR - pika.adapters.blocking_connection: Unexpected connection close detected: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-10-30 13:30:49 - ERROR - client: AMQP Error: Stream connection lost: IndexError('pop from an empty deque')
2024-10-30 13:30:49 - ERROR - client: Error closing connection: 'NoneType' object has no attribute 'clear'
2024-10-30 13:31:09 - INFO - pika.adapters.utils.connection_workflow: Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-10-30 13:31:09 - INFO - pika.adapters.utils.io_services_utils: Socket connected: <socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 40372), raddr=('127.0.0.1', 5672)>
2024-10-30 13:31:09 - INFO - pika.adapters.utils.connection_workflow: Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7e53c1361600>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7e53c1361600> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-10-30 13:31:09 - INFO - pika.adapters.utils.connection_workflow: AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7e53c1361600> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-10-30 13:31:09 - INFO - pika.adapters.utils.connection_workflow: AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7e53c1361600> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-10-30 13:31:09 - INFO - pika.adapters.blocking_connection: Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7e53c1361600> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-10-30 13:31:09 - INFO - pika.adapters.blocking_connection: Created channel=1
2024-10-30 13:31:09 - INFO - client: Connected to RabbitMQ and listening on queue: amq.gen-0jpld1lmUJGVrz7VtnOcCw
2024-10-30 13:31:09 - INFO - client: Sent 'Hi' to server for readiness check.
2024-10-30 13:31:09 - INFO - client: Received response: Hello for request ID: 95c26105-6c68-4efb-8824-f5b09bcd375a
2024-10-30 13:31:09 - INFO - client: Server is ready.
2024-10-30 13:31:13 - INFO - pika.adapters.blocking_connection: Closing connection (200): Normal shutdown
2024-10-30 13:31:13 - INFO - pika.channel: Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7e53c1361600> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-10-30 13:31:13 - ERROR - pika.adapters.utils.io_services_utils: _AsyncBaseTransport._produce() failed, aborting connection: error=IndexError('pop from an empty deque'); sock=<socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 40372), raddr=('127.0.0.1', 5672)>; Caller's stack:
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
2024-10-30 13:31:13 - INFO - pika.adapters.utils.io_services_utils: _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=IndexError('pop from an empty deque'); <socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 40372), raddr=('127.0.0.1', 5672)>
2024-10-30 13:31:13 - INFO - pika.adapters.utils.io_services_utils: Deactivating transport: state=1; <socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 40372), raddr=('127.0.0.1', 5672)>
2024-10-30 13:31:13 - ERROR - pika.adapters.base_connection: connection_lost: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-10-30 13:31:13 - INFO - pika.connection: AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",); pending-error=None
2024-10-30 13:31:13 - INFO - pika.connection: Stack terminated due to StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-10-30 13:31:13 - INFO - pika.adapters.utils.io_services_utils: Closing transport socket and unlinking: state=2; <socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 40372), raddr=('127.0.0.1', 5672)>
2024-10-30 13:31:13 - ERROR - pika.adapters.blocking_connection: Unexpected connection close detected: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-10-30 13:31:13 - ERROR - client: Error closing connection: Stream connection lost: IndexError('pop from an empty deque')
